spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_db?useUnicode=true;characterEncoding=utf8;useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8111
  servlet:
    context-path: /mptest

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
